sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: "https://oss-cn-guangzhou.aliyuncs.com"
    access-key-id: "LTAI5tJuE6BLYYA1xzYokcB3"
    access-key-secret: "SmYgLfU4hLaQ6n1MijTlS0jPHLn9ja"
    bucket-name: "web-tinyproject"
spring:

  redis:
    database: 10
    host: localhost
    port: 6379
