sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: "https://oss-cn-guangzhou.aliyuncs.com"
    access-key-id: "LTAI5tQJZ1SZM6Cyy12FiYJJ"
    access-key-secret: "QfpHfJERuUTY23E6yl6v1rw9FQmT0K"
    bucket-name: "web-tinyproject"
